language: go

go: "1.10"

services:
  - postgresql
  - mysql

env:
- SQLKIT_DRIVER=sqlite3 SQLKIT_CONN=":memory:"
- SQLKIT_DRIVER=mysql SQLKIT_CONN="travis@127.0.0.1/sqlkit"
- SQLKIT_DRIVER=postgresql SQLKIT_CONN="postgresql://travis@127.0.0.1/sqlkit"

before_install:
- mysql -e 'CREATE DATABASE sqlkit;'
- psql -c 'create database sqlkit;' -U postgres

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u gopkg.in/alecthomas/gometalinter.v2
- gometalinter.v2 --install
- mv $GOPATH/bin/gometalinter.v2 $GOPATH/bin/gometalinter
- dep ensure

script:
- make test

after_script:
- bash <(curl -s https://codecov.io/bash) -f coverage.txt

cache:
  directories:
  - vendor
