language: go

go: "1.12.7"

services:
  - postgresql
  - mysql

env:
- SQLKIT_DRIVER=sqlite3 SQLKIT_CONN=":memory:"
- SQLKIT_DRIVER=mysql SQLKIT_CONN="root@tcp(127.0.0.1:3306)/sqlkit"
- SQLKIT_DRIVER=postgres SQLKIT_CONN="user=travis dbname=sqlkit sslmode=disable"

before_install:
- mysql -e 'CREATE DATABASE sqlkit;'
- psql -c 'create database sqlkit;' -U postgres

script:
- make test

after_script:
- bash <(curl -s https://codecov.io/bash) -f coverage.txt

cache:
  directories:
  - vendor
